### ISSUE TITLE
Output being cut off

### ISSUE THREAD

**Issue by lifeinData** [mapbox/geojson-quirks#4]
Hi Perry,

I'm having some issues with the ouput being cut off by using the **geojson-quirks --add-id-from-property TEXT** function.

In particular I'm using [this geojson file](https://raw.githubusercontent.com/adamw523/toronto-geojson/master/simple.geojson). Where I'm trying to define the id using HOOD feature from properties. 

I'm using this command:

C:\Users\a\Police Maps>geojson-quirks toronto_hood.geojson --add-id-from-property HOOD

It seems to run and work but the output is cut off and I'm not aware of how I would (1) use your console functions in a python script so I can output into a notepad and (2) how to output to a notepad using your console functions

![image](https://user-images.githubusercontent.com/29694974/42302439-bb58a8d2-7fcf-11e8-8e2d-1660fa894ea9.png)

As you can see from the screen shot, the ID does take the form of the HOOD but then it also cuts off. 

@perrygeo Any advice would be helpful. Thank you.

**Comment by perrygeo** [comment]
`geojson-quirks` is intended to be a command line tool and is designed to output data to the standard output stream. The cut off you're seeing is a result of your console truncating the output. Instead of printing to the console, you can redirect the output to a file by adding ` > output.geojson` at the end of the command.

For use in Python, I would recommend using the `tweak_feature` function: https://github.com/mapbox/geojson-quirks/blob/master/geojson_quirks/tweak.py
